baseURL = 'https://idealqq123.github.io/'
languageCode = 'en-us'
title = 'Xiaolong Wu'
theme = 'hugo-xmin'

[params]
  author = "Xiaolong Wu（吴肖龙）"
  title_position = "Ph.D, Associate professor"
  affiliation = "School of Information Engineering, Nanchang University; Shenzhen Research Institute, Huazhong University of Science and Technology.  | 南昌大学信息工程学院; 深圳华中科技大学研究院"
  email = "wxl6895209@gmail.com"
  github = "IdealQQ123"
  scholar = "https://teacher.ncu.edu.cn/publish/wxl/"
  customCSS = ["/css/custom.css"]

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

[[menu.main]]
  name = "Publications"
  url = "/publications/"
  weight = 3

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 4
